version: "3.8"
networks:
    caddy_network:
        external: true
services:
    jkbrodev:
        build: .
        container_name: jkbrodev
        ports:
            - 3000:3000
        command: bun run preview
        networks: 
          - caddy_network
